apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: gpu-inference-default
spec:
  amiFamily: AL2023
  role: gpu-platform-prod-gpu-inference
  subnetSelectorTerms:
    - tags:
        Tier: private
  securityGroupSelectorTerms:
    - tags:
        Name: gpu-platform-prod-nodes-sg
  tags:
    workload-type: gpu-inference
