apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: training-platform
resources:
  - namespace.yaml
  - priorityclass.yaml
  - resourcequota.yaml
  - networkpolicy-default-deny.yaml
