apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project-platform-core.yaml
  - project-gpu-platform.yaml
  - project-inference.yaml
  - project-training.yaml
  - project-security.yaml
  - project-observability.yaml
  - project-tenancy.yaml
